config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    get 'bookings/index'
  end
  devise_for :users
  root to: 'pages#home'

  resources :socks, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
  namespace :dashboard do
    resources :bookings, only: [:index]
  end
  resources :users, only: [:show]

  resources :bookings, only: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :sock

  enum status: [ :pending, :confirmed, :rejected ]
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/sock.rb
class Sock < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users_as_owner, through: :bookings
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # include PgSearch::Model
  # multisearchable against: %i[name description color address ]

  validates :name, presence: true
  validates :description, presence: true
  validates :color, presence: true
  validates :size, presence: true
  validates :size, presence: true, numericality: { only_float: true }
  validates :price, presence: true
  validates :price, numericality: { only_integer: true }
  # validates :photo, presence: true
  validates :style, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :socks
  has_many :bookings_as_owner, through: :socks, source: :bookings
  has_one_attached :photo

  # validates :username, presence: true
  # validates :username, uniqueness: true
  # validates :location, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    socks_path
  end

  include Pundit

  def after_sign_in_path_for(resource)
    socks_path
  end
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo, :location])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo, :location])
  end


  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @sock = Sock.find(params[:sock_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @sock = Sock.find(params[:sock_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.sock = @sock
    authorize @booking
    if @booking.save
      redirect_to dashboard_bookings_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)

    redirect_to dashboard_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/dashboard/bookings_controller.rb
class Dashboard::BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
    @bookings_as_owner = policy_scope([:dashboard, Booking])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/socks_controller.rb
class SocksController < ApplicationController
  before_action :authenticate_user!, except: [ :home, :index, :show]
  before_action :set_sock, only: [:show, :edit, :update, :destroy]

  def index
    # @socks = Sock.all
    @socks = policy_scope(Sock)
    if params[:query].present?
      sql_query = " \
      socks.name @@ :query \
      OR socks.description @@ :query \
      OR socks.color @@ :query \
      OR socks.style @@ :query \
      OR socks.address @@ :query \
      "
      @socks = Sock.where(sql_query, query: "%#{params[:query]}%")
    else
      @socks = policy_scope(Sock)
    end
    # the `geocoded` scope filters only socks with coordinates (latitude & longitude)
    @markers = @socks.geocoded.map do |sock|
      {
        lat: sock.latitude,
        lng: sock.longitude,
        info_window: render_to_string(partial: "info_window", locals: { sock: sock }),
        image_url: helpers.asset_url("sockspink.png")
      }
    end
  end

  def show
    @socks = policy_scope(Sock)
    @markers = @socks.where(id: params[:id]).geocoded.map do |sock|
      {
        lat: sock.latitude,
        lng: sock.longitude,
        info_window: render_to_string(partial: "info_window", locals: { sock: sock }),
        image_url: helpers.asset_url("sockspink.png")
      }
    end
  end

  def new
    @sock = Sock.new
    authorize @sock
  end

  def create
    @sock = Sock.new(sock_params)
    @sock.user = current_user
    authorize @sock
    if @sock.save
      redirect_to @sock, notice: 'Sock added!'
    else
      render :new
    end
  end

  private

  def sock_params
    params.require(:sock).permit(:name, :description, :color, :size, :price, :photo, :style, :address)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_sock
    @sock = Sock.find(params[:id])
    authorize @sock
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [ :home, :index, :show]

  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h2>Choose the duration and you're all set!</h2>
<div class="container">
  <%= simple_form_for [@sock, @booking] do |f| %>
    <%= f.input :start_date, html5: true %>
    <%= f.input :end_date, html5: true %>
    <%= f.submit class: 'btn-ghost' %>
  <% end %>
</div>

app/views/dashboard/bookings/index.html.erb
<div class="container">
  <ul class="nav tabs-underlined" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="active tab-underlined" id="home-tab" data-toggle="tab" href="#my-socks" role="tab" aria-controls="home" aria-selected="true">My Socks</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="tab-underlined" id="profile-tab" data-toggle="tab" href="#bookings" role="tab" aria-controls="profile" aria-selected="false">Bookings</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="tab-underlined" id="profile-tab" data-toggle="tab" href="#requests" role="tab" aria-controls="profile" aria-selected="false">Requests</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">

    <div class="tab-pane fade py-3 show active" id="my-socks" role="tabpanel" aria-labelledby="home-tab">
      <div class="container mb-3">
        <% if current_user.socks.present? %>
          <% current_user.socks.each do |sock| %>
            <div class="card-product mb-3">
              <%= cl_image_tag sock.photo.attached? ? cl_image_path(sock.photo.key) : image_path(sock.photo_url) %>
              <div class="card-product-infos">
                <h2><%= link_to sock.name.capitalize, sock %></p></h2>
                <p><%= sock.description.capitalize %></p>
                <p>Size: <%= sock.size %></p>
                <p>Style: <%= sock.style.capitalize %></p>
                <p>Color: <%= sock.color.capitalize %></p>
                <p>Price: <%= sock.price %></p>
              </div>
            </div>
          <% end %>
        <% else %>
        <div class="container">
          <h2>You haven't uploaded any socks yet!</h2>
        </div>
        <% end %>
      </div>
    </div>


    <div class="tab-pane fade py-3 mb-3" id="bookings" role="tabpanel" aria-labelledby="profile-tab">
      <div class="container mb-3">
        <% if current_user.bookings.present? %>
          <% @bookings.each do |booking| %>
            <% if booking.status == 'pending' %>
              <div class="container">
                <h2>Pending</h2>
                <div class="card-product mb-3">
                  <%= cl_image_tag booking.sock.photo.attached? ? cl_image_path(booking.sock.photo.key) : image_path(booking.sock.photo_url) %>
                  <div class="card-product-infos">
                    <h2><%= booking.sock.name.capitalize %></h2>
                    <p><%= booking.sock.description.capitalize %></p>
                    <p><%= booking.sock.size %></p>
                    <p><%= booking.sock.style.capitalize %></p>
                    <p><%= booking.sock.color.capitalize %></p>
                    <p><%= booking.sock.price %></p>
                  </div>
                </div>
              </div>
            <% elsif booking.status == 'confirmed' %>
              <div class="container">
                <h2>Confirmed</h2>
                <div class="card-product mb-3">
                  <%= cl_image_tag booking.sock.photo.attached? ? cl_image_path(booking.sock.photo.key) : image_path(booking.sock.photo_url) %>
                  <div class="card-product-infos">
                    <h2><%= booking.sock.name.capitalize %></h2>
                    <p><%= booking.sock.description.capitalize %></p>
                    <p><%= booking.sock.size %></p>
                    <p><%= booking.sock.style.capitalize %></p>
                    <p><%= booking.sock.color.capitalize %></p>
                    <p><%= booking.sock.price %></p>
                  </div>
                </div>
              </div>
           <% end %>
          <% end %>
        <% else %>
          <div class="container">
            <h2>You haven't booked any socks yet!</h2>
          </div>
        <% end %>
      </div>
    </div>



    <div class="tab-pane fade py-3" id="requests" role="tabpanel" aria-labelledby="profile-tab">
      <div class="container mb-3">
        <% if @bookings_as_owner.where(status: "pending").present? %>
        <div class="card-product mb-3">
          <% @bookings_as_owner.where(status: "pending").each do |booking| %>
            <%= cl_image_tag booking.sock.photo.attached? ? cl_image_path(booking.sock.photo.key) : image_path(booking.sock.photo_url) %>
            <div class="card-product-infos">
            <p>From: <%= booking.start_date %></p>
            <p>Until: <%= booking.end_date %></p>
            <p>Requested by: <%= booking.user.email %></p>
            <div style="display: flex">
              <%= simple_form_for(booking) do |f| %>
                <%= f.input :status, input_html: {value: "confirmed" }, as: :hidden %>
                <%= f.submit "Accept", class: "btn-ghost mr-2" %>
              <% end %>
              <%= simple_form_for(booking) do |f| %>
                <%= f.input :status, input_html: {value: "rejected" }, as: :hidden %>
                <%= f.submit "Reject", class: "btn-ghost" %>
              <% end %>
            </div>
           </div>
          <% end %>
        <% else %>
          <div class="container">
            <h2>No pending requests!</h2>
          </div>
        <% end %>
      </div>
    </div>
</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Air Socks - If the sock fits...</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


      <%= yield %>


    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hero-image">
  <div class="hero-text">
    <div class="mb-5">
      <h1>Looking for a sock or two? We have you covered.</h1>
    </div>
    <div class="mt-3">
      <%= link_to "See our socks!", socks_path, class: 'btn-slide' %>
    </div>
  </div>
</div>
<div>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 d-flex justify-content-center align-items-center">
        <div class="mt-4">
          <h2>Step in a puddle? Got a hole in your sock? Dressing to impress?</h2>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card my-3">
          <div class="card-body">
            <h5 class="card-title">Find the perfect sock<i class="ml-2 fas fa-search"></i></h5>
            <p class="card-text">Renting socks has never been easier. Start searching and find the right sock for you today.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="card my-3">
          <div class="card-body">
            <div class="d-flex align-items-center">
              <h5 class="card-title">Looking to rent out your socks?<i class="ml-2 fas fa-money-bill-wave"></i></h5>
            </div>
            <p class="card-text">Socks have become the future of side-hustles. Log in or sign up and make your socks available today.</p>
          </div>
      </div>
      </div>
      <div class="col-sm-6 d-flex justify-content-center align-items-center">
        <div class="mt-2 mb-4">
          <h2>Find the perfect sock to fit your needs.</h2>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer">
  <p>Contact Us: airsocks@socks.com</p>
  <p>+81 080 555 1800</p>
  <p> Air Socks ©</p>
  <p>Made with love by <a href="https://github.com/anthonytjohnson">Anthony</a>, <a href="https://github.com/deetorz">Derek</a>, and <a href="https://github.com/melpicardal
">Mel</a></p>
</div> %>


<div class="footer">
  <div class="footer-links">
    <span>123 Sesame Street<span>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-socks"></i> by
    <%= link_to "Derek", "https://github.com/deetorz" %>,
    <%= link_to "Anthony", "https://github.com/anthonytjohnson" %>, and
    <%= link_to "Mel", "https://github.com/melpicardal" %>.


  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to socks_path, class: "navbar-brand d-flex" do %>
      <p class="nav-name"><i class="ml-1 fas fa-socks"></i></p>
      <p class="nav-name ml-2">Air Socks</p>
    <% end %>

    <%= form_tag socks_path, method: :get do %>
      <div class="d-flex">
        <div>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a sock"
          %>
        </div>
        <div>
          <%= submit_tag "Search", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <span class="mr-3"><%= link_to 'Create a sock listing', new_sock_path, class: 'mr-3 btn-ghost' %></span>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", socks_path, class: 'mr-3 btn-ghost' %>
        </li>

        <li class="nav-item active">
          <div class="d-flex align-items-center">
            <% if current_user.present? %>
              <p class="m-0"><%= current_user.username.present? ? "#{current_user.username}" : "#{current_user.email}" %></p>
            <% end %>
          </div>
        </li>

        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.attached? ? cl_image_path(current_user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-bordered dropdown-toggle ml-2", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Socks", dashboard_bookings_path, class: "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn-ghost" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/socks/_form.html.erb
<div class="container">
  <%= simple_form_for(@sock) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :color %>
      <%= f.input :size %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <%= f.input :style %>
      <%= f.input :address %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn-ghost' %>
      <%= link_to 'Back', socks_path, class: 'btn-ghost' %>
    </div>
  <% end %>
</div>

app/views/socks/_info_window.html.erb
<h2><%= link_to sock.name.capitalize, sock %></h2>
<p>Price: ¥<%= sock.price %></p>
<%= cl_image_tag sock.photo.attached? ? cl_image_path(sock.photo.key, :width => 120, :height => 120, :crop => :limit
) : image_path(sock.photo_url, :width => 120, :height => 120, :crop => :limit
) %>

app/views/socks/index.html.erb
<div class="container d-flex mt-5">
  <div class="row">
      <% @socks.each do |sock| %>
        <div class="col">
          <div class="card-product mb-3">
            <%= cl_image_tag sock.photo.attached? ? cl_image_path(sock.photo.key, :crop=>"lfill") : image_path(sock.photo_url) %>
            <div class="card-product-infos text-center">
              <h2><%= link_to sock.name.capitalize, sock %></h2>
              <p><%= sock.description %></p><br>
              <span><strong> ¥<%= sock.price %></strong></span>
              <div class='mt-5'>
                <span><%= link_to 'Show', sock, class: 'btn-ghost' %></span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>

    <div class="container">
      <div class="sticky">
        <div id="map"
          style="width: 600px; height: 50vh; border-radius: 0 0 30% 0;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>

</div>

app/views/socks/new.html.erb
<div class="container">
  <h1 class="text-center mt-3">Add a sock</h1>

  <%= render 'form', sock: @sock %>

</div>

app/views/socks/show.html.erb
<div class="container-sock">
  <div class="row py-2">
    <div class="col-8">
      <div>
        <h2><strong><%= @sock.name %></strong></h2>
      </div>
      <div class="d-flex border-right">
        <div class="container-sock-img">
          <%= cl_image_tag @sock.photo.attached? ? cl_image_path(@sock.photo.key, :crop=>"lfill") : image_path(@sock.photo_url) %>
        </div>
        <div class="ml-4 mt-5">
          <div class="mb-2 d-flex align-items-center">
            <%= cl_image_tag @sock.user.photo.attached? ? cl_image_path(@sock.user.photo.key) : image_path("https://mobilityoi.org/wp-content/uploads/2015/06/Avatar-No-Photo-generic.jpg"), class: "avatar-large" %>
            <p class="ml-2 pt1"><%= @sock.user.username if @sock.user.username.present?  %></p>
          </div>
          <p><strong>Size: </strong><%= @sock.size %></p>
          <p><strong>Color: </strong><%= @sock.color.capitalize %></p>
          <p><strong>Style: </strong><%= @sock.style.capitalize %></p>
          <p><strong>Style: </strong><%= @sock.description %></p>
          <p><strong>Style: </strong>¥<%= @sock.price %></p>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="container">
        <div class="sticky">
          <div id="map"
            style="width: 400px; height: 50vh; border-radius: 0 0 30% 0;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="d-flex align-items-center justify-content-center mt-3 ">
      <% if current_user.nil? || @sock.user_id != current_user.id  %>
        <%= link_to 'Make a booking', new_sock_booking_path(@sock), class: 'btn-slide mr-2'%>
        <%= link_to 'Back', socks_path, class: 'btn-slide' %>
      <% else @sock.user_id == current_user.id %>
        <%= link_to 'Back', socks_path, class: 'btn-slide' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-3">
		<div class="center">
    <%= cl_image_tag @user.photo.attached? ? cl_image_path(@user.photo.key) : image_path(@sock.photo_url) %>

		</div>
		<div class="panel panel-default">
			<div class="panel-heading">Verification</div>
			<div class="panel-body">

        Email <%= @user.email %></br>
				Phone number
			</div>
		</div>
	</div>

	<div class="col-md-9">
		<h2><%= @user.username %></h2>
		<div class="description row-space-3">
			<%= @user.location %>
		</div>
	</div>
</div>